version: "3.9"
name: "bookstore-dev"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
      target: development
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_USER_PASSWORD=${DATABASE_USER_PASSWORD}
      - PYDEVD_DISABLE_FILE_VALIDATION=1
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./api/config:/api/config
      - ./api/apps:/api/apps
      - ./api/manage.py:/api/manage.py
      - ./api/requirements/base.txt:/api/requirements/base.txt
      - ./api/requirements/development.txt:/api/requirements/development.txt
      - ./api/scripts/dev-run.sh:/api/run.sh
      - ./api/pyproject.toml:/api/pyproject.toml
      - ./api/.flake8:/api/.flake8
      - ./api/conftest.py:/api/conftest.py
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data: