name: "bookstore-prod"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
      target: production
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_USER_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "8000:8000"
    restart: always


  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  prod-db-data: