name: "bookstore-prod"

services:
  proxy:
    build: ./proxy
    volumes:
      - static:/static
      - media:/media
    ports:
      - "1337:80"
    depends_on:
      - api
    restart: always

  api:
    build:
      context: api
      dockerfile: Dockerfile
      target: production
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}      
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_USER_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - static:/api/static
      - media:/api/media
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  static:
  media:
  db-data: