# Generated by Django 5.0.6 on 2024-08-28 14:57

import apps.orders.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="new",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="no",
            field=models.SlugField(
                default=apps.orders.helpers.generate_order_number,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
