# Generated by Django 5.0.6 on 2024-09-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_status_alter_order_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="In Progress",
                max_length=255,
            ),
        ),
    ]
