# Generated by Django 5.0.6 on 2024-06-07 09:55

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(
                validators=[apps.core.validators.date_cannot_be_in_future]
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                validators=[apps.core.validators.date_cannot_be_in_future]
            ),
        ),
    ]
