# Generated by Django 5.0.6 on 2024-06-23 08:28

import apps.books.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_author_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.books.helpers.book_image_upload_to_path,
            ),
        ),
    ]
