# Generated by Django 5.0.6 on 2024-06-24 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_author_created_at_author_updated_at_book_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
            preserve_default=False,
        ),
    ]
