# Generated by Django 5.0.6 on 2024-06-27 13:43

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
