[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "test.settings.test"
python_files = ["test_*.py",]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "manage.py",
    "config/*",
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*_tests.py"
]