[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["test_*.py",]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "manage.py",
    "conftest.py",
    "config/*",
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*_tests.py",
    "*/management/commands/*",
    "apps/core/scheme.py",
]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \venv
  | \.venv
  | _build
  | buck-out
  | migrations
  | build
  | dist
)/
'''

[tool.flake8]
exclude = """
    .git,
    .gitignore,
    *.pot,
    *.py[co],
    __pycache__,
    migrations,
    venv,
    .venv,
    .env"
"""
ignore = """
    E121,
    E126,
    E127,
    E128,
    E203,
    E225,
    E226,
    E231,
    E241,
    E251,
    E261,
    E265,
    E302,
    E303,
    E305,
    E402,
    E501,
    E741,
    W291,
    W292,
    W293,
    W391,
    W503,
    W504,
    F403,
    B007,
    B950
"""
per-file-ignores = """
    config/settings/*.py: F405
"""
max-line-length = 88