[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["test_*.py",]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "manage.py",
    "conftest.py",
    "config/*",
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*_tests.py",
    "*/management/commands/*",
    "apps/core/scheme.py",
]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \venv
  | \.venv
  | _build
  | buck-out
  | migrations
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 88
exclude = """
    .git,
    .gitignore,
    *.pot,
    *.py[co],
    __pycache__,
    migrations,
    venv,
    .venv,
    .env"
"""
ignore = """W503"""
per-file-ignores = """
    config/settings/*.py: F403,F405,E501
    config/urls/*.py: F405
"""
