[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.test"
python_files = ["test_*.py",]
addopts = "--cov=. --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "manage.py",
    "conftest.py",
    "config/*",
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*_tests.py",
    "apps/core/scheme.py",
]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | migrations
  | build
  | dist
)/
'''