name: API-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting-and-formatting:
    name: Linting and Formatting
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
    - name: Checkout of the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
        pip install -r requirements/development.txt

    - name: Check formatting with Black
      run: black --check --diff .

    - name: Linting with Flake8
      run: flake8 .

  testing:
    needs: linting-and-formatting

    name: Testing
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout of the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Start containers
        run: docker-compose -f testing.yml up -d --build

      - name: Run tests
        run: docker-compose exec -it bookstore-test-api-1 pytest

      - name: Stop containers
        if: always()
        run: docker-compose -f testing.yml down